dism.exe /online /enable-feature /featurename:IIS-WebServerRole /NoRestart
dism.exe /online /enable-feature /featurename:IIS-WebServer /NoRestart
dism.exe /online /enable-feature /featurename:IIS-CommonHttpFeatures /NoRestart
dism.exe /online /enable-feature /featurename:IIS-HttpErrors /NoRestart
dism.exe /online /enable-feature /featurename:IIS-HttpRedirect /NoRestart
dism.exe /online /enable-feature /featurename:IIS-ApplicationDevelopment /NoRestart
dism.exe /online /enable-feature /featurename:NetFx4Extended-ASPNET45 /NoRestart
dism.exe /online /enable-feature /featurename:IIS-NetFxExtensibility45 /NoRestart
dism.exe /online /enable-feature /featurename:IIS-HealthAndDiagnostics /NoRestart
dism.exe /online /enable-feature /featurename:IIS-HttpLogging /NoRestart
dism.exe /online /enable-feature /featurename:IIS-LoggingLibraries /NoRestart
dism.exe /online /enable-feature /featurename:IIS-RequestMonitor /NoRestart
dism.exe /online /enable-feature /featurename:IIS-HttpTracing /NoRestart
dism.exe /online /enable-feature /featurename:IIS-Security /NoRestart
dism.exe /online /enable-feature /featurename:IIS-RequestFiltering /NoRestart
dism.exe /online /enable-feature /featurename:IIS-Performance /NoRestart
dism.exe /online /enable-feature /featurename:IIS-WebServerManagementTools /NoRestart
dism.exe /online /enable-feature /featurename:IIS-IIS6ManagementCompatibility /NoRestart
dism.exe /online /enable-feature /featurename:IIS-Metabase /NoRestart
dism.exe /online /enable-feature /featurename:IIS-ManagementConsole /NoRestart
dism.exe /online /enable-feature /featurename:IIS-BasicAuthentication /NoRestart
dism.exe /online /enable-feature /featurename:IIS-StaticContent /NoRestart
dism.exe /online /enable-feature /featurename:IIS-DefaultDocument /NoRestart
dism.exe /online /enable-feature /featurename:IIS-WebSockets /NoRestart
dism.exe /online /enable-feature /featurename:IIS-ApplicationInit /NoRestart
dism.exe /online /enable-feature /featurename:IIS-ISAPIExtensions /NoRestart
dism.exe /online /enable-feature /featurename:IIS-ISAPIFilter /NoRestart
dism.exe /online /enable-feature /featurename:IIS-HttpCompressionStatic /NoRestart
dism.exe /online /enable-feature /featurename:IIS-ASPNET45 /NoRestart